[build]
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  DATABASE_URL = "postgresql://placeholder:placeholder@localhost:5432/authstorage"
  REPLIT_DOMAINS = "authstorage-platform.windsurf.build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
